export const PERMISSIONS = {
  CREATE_FORM: 'CREATE_FORM',
  SUBMIT_FORM: 'SUBMIT_FORM',
  VIEW_FORM: 'VIEW_FORM',
  UPDATE_FORM: 'UPDATE_FORM',
  DELETE_FORM: 'DELETE_FORM',

  CREATE_FIELD: 'CREATE_FIELD',
  UPDATE_FIELD: 'UPDATE_FIELD',
  DELETE_FIELD: 'DELETE_FIELD',

  VIEW_SUBMISSIONS: 'VIEW_SUBMISSIONS',
  VIEW_ALL_SUBMISSIONS: 'VIEW_ALL_SUBMISSIONS',
} as const;

export type PermissionType = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
